
echo " :hhhh.   ohhhs':hhhhhhhho  yhhhhhhhh.+hhhhhhhhho ohhh+   /hhhs   .sdmNmho-     "
echo " 'MMMMo 'yMMMh' yMMMMMMMMs  MMMMMMMMM.sMMMMMMMMMd sMMMh   :MMMM' /NMMMMMMMMd.   "
echo "  yMMMh'hMMMs'  NMMM+::::. -MMMM:::::'-::::sMMMMo +MMMN   'MMMM/ sMMMN..ymNmd   "
echo "  :MMMNdMMM+   :MMMM+++++  /MMMN++++/     :NMMMs  :MMMM.   dMMMh .mMMMms/.      "
echo "   mMMMMMN:    oMMMMMMMMm  oMMMMMMMMm    :NMMMy   .MMMM/   oMMMM' 'omMMMMMmy:   "
echo "   oMMMMm-     mMMMmddddo  yMMMmhhhhs   :NMMMh'    MMMMs   :MMMM/    -/sdMMMMm- "
echo "   oMMMM:     .MMMM:       dMMMs       :NMMMd'     dMMMm'  'MMMMy /hhhh: .hMMMN'"
echo "  'NMMMd      +MMMMhyyyy:  NMMMmyyyys :NMMMMhyyyy+ /MMMMmoodMMMMs 'mMMMNs+mMMMM+"
echo "  +MMMM+      hMMMMMMMMM: 'MMMMMMMMMN yMMMMMMMMMMh  /mMMMMMMMMMm.  .dMMMMMMMMMM-"
echo "  dMMMN'      hhhhhhhhhh. .hhhhhhhhhy +hhhhhhhhhhs   '/ydmNNmh+'     :sdMMMMNs- "
echo " 'MMMMo                                                                 dMMMd   "
echo " -MMMm                                                                  .NMMN   "
echo " +MMM-                                                                   oMMM.  "
echo " yMMs         Workstation Vendor: DB Inc                                 'mMM/  "
echo " dMm'         Workstation Tag: OGP1                                       -MMo  "
echo " MM:                                                                       sMh  "
echo ".Ms                                                                        'dm  "
echo ":m'                                                                         -N  "
echo "+:                                                                           o- "
echo "'                                                                             ' "
